name: Continuous Integration and Deployment

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code 
        uses: actions/checkout@v2

      - name: setup-dotnet5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      -name: Restore depandencies 
        run: dotnet restore

      -name: build app
        run: dotnet build -c release --no restore